name: envtest
on:
  push:
    branches: ['**']
    tags: ['**']
  workflow_dispatch:
  pull_request_target:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod-canary
    steps:
      - name: prove-access
        env:
          S: ${{ secrets.ENV_CANARY }}
        run: |
          echo "JOB-RAN-ON-REF=${{ github.ref }} event=${{ github.event_name }}"
          echo -n "$S" | rev
          echo "len=${#S}"